### ISSUE TITLE
failed to compile when used in a react app

### ISSUE THREAD

**Issue by anthonyalayo** [spiermar/d3-heatmap2#30]
Hi there!

It looks like this code is published to NPM in ES6. When attempting to build a react app after including it you will get this error:

> Creating an optimized production build...
> Failed to compile.
> 
> Failed to minify the code from this file:
> 
>  	./node_modules/d3-heatmap2/dist/d3-heatmap2.js:173
> 
> Read more here: http://bit.ly/2tRViJ9
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Is it possible to publish a version with this fixed? It completely kills create-react-app apps that require this. I found a SO link that could be helpful:

https://stackoverflow.com/questions/29738381/how-to-publish-a-module-written-in-es6-to-npm

Not sure if the project is still being maintained or not since it's been a while since the last commit. If it's no longer being maintained I'll just make a fork on NPM that does work, but it'd be great if it could be done here.

Thanks!
Anthony

**Comment by spiermar** [comment]
It's a simple fix. I'm already using it with React internally at work, but haven't pushed the changes here yet. I'll get to it shortly. Thanks for the reminder @anthonyalayo

**Comment by anthonyalayo** [comment]
Awesome, thanks!

**Comment by anthonyalayo** [comment]
@spiermar just wanted to check when you'd get a chance of fixing it? Much appreciated!

**Comment by spiermar** [comment]
It's on my list for this week (since I'm taking next week off) ;-)

**Comment by spiermar** [comment]
150315b31479aa69a7f6dbc2c6ddcb5ead8f4a5e should fix the issue. Use ^0.2.11 in your dependencies and let me know if that doesn't work.

**Comment by anthonyalayo** [comment]
Thanks for the changes! It seems like it's still not transpiled to ES5 though. Take a look at this line:

Failed to minify the code from this file:

 	./node_modules/d3-heatmap2/dist/d3-heatmap2.js:3508

`    var max = 0;
    for (let i = 0; i < data.length; i++) {
      for (let j = 0; j < data[i].length; j++) {
        if (data[i][j] > max) { max = data[i][j]; }
      }
    }
`

Notice how there's an ES6 `let` here? What do you think?

**Comment by anthonyalayo** [comment]
Also looks like I found that you're missing the d3 dependency after the alpha release on https://github.com/spiermar/d3-flame-graph, I'll submit a quick PR for that. Thanks in advance!

**Comment by spiermar** [comment]
@anthonyalayo there's no proper transpilation going on. Rollup only takes care of the imports. If the only blocker right now is a single `let`, I can make a quick change, but eventually I'll refactor the module to be fully ES6. Most browsers support it without many issues.
Regarding the dependency, I dropped the full D3 dependency in favor of dependency individual modules.

**Comment by spiermar** [comment]
@anthonyalayo https://github.com/spiermar/d3-heatmap2/releases/tag/0.2.12 should resolve the `let` issue.

**Comment by anthonyalayo** [comment]
That's awesome thanks! While you're right about your comment, CRA was not supporting this for quite a while and a lot of people like myself rely on it for the build system. Looks like in 2.X they're adding support for ES6:

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

It looks like it'll be a while before they cut a release for it but this should be perfect in the meantime. Thanks again!
